services:
  db:
    image: postgres:15-alpine
    container_name: football_live_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_live
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U postgres"]
      #interval: 5s
      #timeout: 5s
      #retries: 5
  
  adminer:
    image: adminer
    container_name: football_live_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data: